name: Check all links in the repository
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  run:
    name: Check Links
    uses: iterative/link-check/.github/workflows/link-check-all.yml@master
